name: Build and Publish Python Package

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Python distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel numpy scipy matplotlib
        pip install .
    - name: Build binary wheel and source tarball
      run: |
        python setup.py sdist bdist_wheel

# For more information on changing these actions see:
# - https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-workflows
# - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows