name: Build Python Package

on: push

jobs:
  build:
    name: Build Python distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install setuptools wheel
    - name: Build binary wheel and source tarball
      run: |
        python setup.py sdist bdist_wheel
